authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<pk>/', basketapp.basket_item_add, name='add'),
    path('remove/<pk>/', basketapp.basket_item_remove, name='remove')
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<pk>/', mainapp.products, name='category'),
    path('product/<pk>', mainapp.product, name='product')
]

myinternetshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', mainapp.main, name="main"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contacts, name="contacts"),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Product name', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='Short desc.', max_length=60, blank=True)
    description = models.TextField(verbose_name='Detailed desc.', blank=True)
    price = models.DecimalField(verbose_name='Price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Amount', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Product, ProductCategory
from basketapp.models import BasketItem


# Create your views here.
def main(request):
    products = Product.objects.all()
    title = 'Home page'
    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    print(pk)

    basket = []
    if request.user.is_authenticated:
        basket = BasketItem.objects.filter(user=request.user)

    title = 'Catalog'
    categories = ProductCategory.objects.all()

    if pk:
        if pk == '0':
            category = {'name': 'ALL PRODUCTS'}
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'categories_list': categories,
            'category': category,
            'products': products,
            'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)

    else_products = Product.objects.all().order_by('price')
    content = {
        'title': title,
        'categories_list': categories,
        'products': else_products
    }
    return render(request, 'mainapp/catalog.html', content)


def contacts(request):
    title = 'Contacts'
    content = {'title': title}
    return render(request, 'mainapp/contact.html', content)


def getBasketItems(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def product(request, pk):
    title = 'products'
    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': getBasketItems(request.user),
    }
    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<!--<div class="categories_list">-->
    <!--<ul>-->
        <li>
            <a href="{% url 'products:category' 0 %}"
               class="{% if request.resolver_match.kwargs.pk == '0' %}
                   active
                   {% endif %}">
                ALL PRODUCTS
            </a>
        </li>
        {% for category in categories_list %}
        <li>
            <a href="{% url 'products:category' category.pk %}"
               class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                        active
                        {% endif %}">
                {{category.name}}
            </a>
        </li>
        {% endfor %}
    <!--</ul>-->
<!--</div>-->

mainapp/templates/mainapp/includes/inc_header-social.html
<div class="header_social">
    {% for link in links_header %}
    <a href="{{link.href}}">
        {{ link.name }}
    </a>
    {% endfor %}
</div>

mainapp/templates/mainapp/includes/inc_menu.html
<div class="menu">
    <ul>
        <li>MENU</li>
        <li><a href="{% url 'main' %}">HOME</a></li>
        <li>
            <a href="{% url 'products:index' %}"
               class="{% if request.resolver_match.namespace == 'products' %}
                active
                {% endif %}">
                CATALOG
            </a>
        </li>
        {% include 'mainapp/includes/inc_categories_menu.html' %}
        <li><a href="{% url 'contacts' %}">CONTACTS</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
        <li>
            <a href="{% url 'basket:view' %}">
            <span>
                {% if basket %}
                    {{ basket.0.total_cost|floatformat:0 }} $
                    {{ basket.0.total_quantity }} els
                {% endif %}
            </span>
            </a>
        </li>
    </ul>

</div>