authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<pk>/', basketapp.basket_item_add, name='add'),
    path('remove/<pk>/', basketapp.basket_item_remove, name='remove')
]

myinternetshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', mainapp.main, name="main"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contacts, name="contacts"),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


# Create your models here.
class BasketItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

    def get_product_cost(self):
        return self.product.price * self.quantity

    def get_total_quantity(self):
        _items = BasketItem.objects.filter(user=self.user)
        _total_quantity = sum(list(map(lambda x: x.quantity, _items)))
        return _total_quantity

    def get_total_cost(self):
        _items = BasketItem.objects.filter(user=self.user)
        _total_cost = sum(list(map(lambda x: x.product_cost, _items)))
        return _total_cost

basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import BasketItem
from mainapp.models import Product


# Create your views here.
def basket(request):
    content = {}
    return render(request, 'basketapp/basket.html', content)


def basket_item_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    old_basket_item = BasketItem.objects.filter(user=request.user, product=product)

    if old_basket_item:
        old_basket_item[0].quantity += 1
        old_basket_item[0].save()
    else:
        new_basket_item = BasketItem(user=request.user, product=product)
        new_basket_item.quantity += 1
        new_basket_item.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_item_remove(request):
    content = {}
    return render(request, 'basketapp/basket.html', content)


def basket(request):
    title = 'корзина'
    basket_items = BasketItem.objects.filter(user=request.user).order_by('product__category')
    content = {
        'title': title,
        'basket_items': basket_items,
    }
    return render(request, 'basketapp/basket.html', content)


def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

basketapp/templates/basketapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
    <div class="basket_container">
        <div class="h2 text-center head">
            Your basket,
            {% if user.first_name %}
            {{ user.first_name|title}}
            {% else %}
            User
            {% endif %}
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="basket_list">
    {% for item in basket_items %}
    <div class="basket_record">
        <img src="/media/{{ item.product.image }}"
             alt="{{ item.product.short_desc }}">
        <span class="category_name">{{ item.product.category.name }}</span>
        <span class="product_name">{{ item.product.name }}</span>
        <span class="product_price">{{ item.product.price }}&nbsp$</span>
        <input type="number" name="{{ item.pk }}"
               min="0"
               value="{{ item.quantity }}">
        <span class="product_cost">{{ item.cost }}&nbsp$</span>
        <button class="btn btn-round">
            <a href="{% url 'basket:remove' item.pk %}" class="">
                DELETR
            </a>
        </button>
    </div>
    {% endfor %}
    {% if basket_items %}
    <div class="basket_summary">
        You have {{ basket_items.0.total_quantity }} items that cost
        {{ basket_items.0.total_cost }} $
    </div>
    {% endif %}
    <button class="btn btn-round">
        <a href="{% url 'main' %}">HOME</a>
    </button>
</div>
{% endblock %}