authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<pk>/', basketapp.basket_item_add, name='add'),
    path('remove/<pk>/', basketapp.basket_item_remove, name='remove')
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<pk>/', mainapp.products, name='category'),
    path('product/<pk>', mainapp.product, name='product')
]

myinternetshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', mainapp.main, name="main"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contacts, name="contacts"),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Product name', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='Short desc.', max_length=60, blank=True)
    description = models.TextField(verbose_name='Detailed desc.', blank=True)
    price = models.DecimalField(verbose_name='Price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Amount', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Product, ProductCategory
from basketapp.models import BasketItem


# Create your views here.
def main(request):
    products = Product.objects.all()
    title = 'Home page'
    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    print(pk)

    basket = []
    if request.user.is_authenticated:
        basket = BasketItem.objects.filter(user=request.user)

    title = 'Catalog'
    categories = ProductCategory.objects.all()

    if pk:
        if pk == '0':
            category = {'name': 'ALL PRODUCTS'}
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'categories_list': categories,
            'category': category,
            'products': products,
            'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)

    else_products = Product.objects.all().order_by('price')
    content = {
        'title': title,
        'categories_list': categories,
        'products': else_products
    }
    return render(request, 'mainapp/catalog.html', content)


def contacts(request):
    title = 'Contacts'
    content = {'title': title}
    return render(request, 'mainapp/contact.html', content)


def getBasketItems(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def product(request, pk):
    title = 'products'
    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': getBasketItems(request.user),
    }
    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title|title %}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!--<link rel="stylesheet" href="style_for_basket.css">-->
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="header_index">
            <div class="logo">
                <img src="{% static 'img/index/logo.png' %}" alt="Logo" title="logo">
                {% block header-social %}
                    {% include 'mainapp/includes/inc_header-social.html' %}
                {% endblock %}
            </div>
            {% block welcome--index %}

            {% endblock %}
        </div>
    <!--</div>-->
    <div class="main">
        <div class="aside">
            {% block menu %}
                {% include 'mainapp/includes/inc_menu.html' %}
            {% endblock %}
        </div>

        {% block content %}
        {% endblock %}

        <div class="brand_index">
            <img src="{% static 'img/index/brands/dji.png' %}" alt="">
            <img src="{% static 'img/index/brands/flyers.png' %}" alt="">
            <img src="{% static 'img/index/brands/parrot.png' %}" alt="">
            <img src="{% static 'img/index/brands/hovercast.png' %}" alt="">
            <img src="{% static 'img/index/brands/syma.png' %}" alt="">
            <img src="{% static 'img/index/brands/qdcam.png' %}" alt="">
        </div>

        <div class="instagram">
            <div class="pict">
                <img src="img/index/inst.png" alt="">
                <p>Instagram feed: <a href="">#quadrofly</a></p>
            </div>
            <div class="photo">
                <img src="{% static 'img/index/instagram/1.jpg' %}" alt="">
                <img src="{% static 'img/index/instagram/2.jpg' %}" alt="">
                <img src="{% static 'img/index/instagram/3.jpg' %}" alt="">
                <img src="{% static 'img/index/instagram/4.jpg' %}" alt="">
                <img src="{% static 'img/index/instagram/5.jpg' %}" alt="">
                <img src="{% static 'img/index/instagram/6.jpg' %}" alt="">
            </div>
        </div>

        <div class="socio">
            <a href="">
                <div class="fb">
                    <img src="{% static 'img/index/socio/fb.png' %}" alt="">
                </div>
            </a>
            <a href="">
                <div class="tw">
                    <img src="{% static 'img/index/socio/tw.png' %}" alt="">
                </div>
            </a>
            <a href="">
                <div class="pin">
                    <img src="{% static 'img/index/socio/pin.png' %}" alt="">
                </div>
            </a>
        </div>
    </div>
    {% block footer %}
    <div class="footer">
        <div class="up_footer">
            <div>
                <h3>Category</h3>
                <ul>
                    <li>Home</li>
                    <li>about us</li>
                    <li>eshop</li>
                    <li>Features</li>
                    <li>new collections</li>
                    <li>blog</li>
                    <li>contact</li>
                </ul>
            </div>
            <div>
                <h3>Our Account</h3>
                <ul>
                    <li>Your Account</li>
                    <li>Personal information</li>
                    <li>Addresses</li>
                    <li>Discount</li>
                    <li>Orders history</li>
                    <li>Addresses</li>
                    <li>Search Terms</li>
                </ul>
            </div>
            <div>
                <h3>Our Support</h3>
                <ul>
                    <li>Site Map</li>
                    <li>Search Terms</li>
                    <li>Advanced Search</li>
                    <li>Mobile</li>
                    <li>Contact Us</li>
                    <li>Mobile</li>
                    <li>Addresses></li>
                </ul>
            </div>
            <div>
                <h3>Newsletter</h3>
                <p>Join thousands of other people subscribe to our news</p>
                <form action="">
                    <input type="text" placeholder="INSERT EMAIL">
                    <input type="submit" value="SUBMIT">
                </form>
                <div>
                    <img src="{% static 'img/index/footer/aex.png' %}" alt="">
                    <img src="{% static 'img/index/footer/mastercard.png' %}" alt="">
                    <img src="{% static 'img/index/footer/maestro.png' %}" alt="">
                    <img src="{% static 'img/index/footer/paypal.png' %}" alt="">
                    <img src="{% static 'img/index/footer/discover.png' %}" alt="">
                    <img src="{% static 'img/index/footer/visa.png' %}" alt="">
                </div>
            </div>
            <div>
                <h3>About us</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque nobis quidem, atque. Nam
                    laboriosam
                    labore, corporis necessitatibus a, debitis. Eum nostrum, dignissimos quisquam quae molestias
                    explicabo quia quas sint voluptatum?</p>
                <h4>Phone: <span>1-999-342-9876</span></h4>
                <h4>e-mail: <span>info@surfhouse.com</span></h4>
            </div>
        </div>
        <div class="down_footer">
            <p>&copy; 2017 QUADROFLY. All rights reserved - Designed by ID|54</p>
            <div class="footer_social">
                <a href=""> <!-- <img src="img/index/footer/fb.png" alt=""> --> </a>
                <a href=""> <!-- <img src="img/index/footer/tw.png" alt=""> --> </a>
                <a href=""> <!-- <img src="img/index/footer/pin.png" alt=""> --> </a>
                <a href=""> <!-- <img src="img/index/footer/gplus.png" alt=""> --> </a>
                <a href=""> <!-- <img src="img/index/footer/inst.png" alt=""> --> </a>
                <a href=""> <!-- <img src="img/index/footer/tumblr.png" alt=""> --> </a>
                <a href=""> <!-- <img src="img/index/footer/rss.png" alt=""> --> </a>
            </div>
        </div>
    </div>
    {% endblock %}
</div>
</body>
</html>

mainapp/templates/mainapp/catalog.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}


{% block content %}
<div class="content">
    <h4>Home >> <span>Catalog</span></h4>
    <div class="offer">

        {% for product in products %}
        <div>
            <a href="{% url 'products:product' product.pk %}">
                <img src="/media/{{ product.image }}" alt="">
            </a>
            <span><a href="">{{ product.name|upper }}</a></span>
            <span>$.{{ product.price }}</span>
            <!--<span> {{ product.category.name}}</span>-->
            <a href="{% url 'basket:add' product.pk %}" class="button-order">Order</a>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="content">
    <h4>Home >> <span>Contact us</span></h4>
    <div class="contact_form">
        <form action="">
            <h3>FULL NAME*</h3>
            <input type="text" placeholder="e.g. robert smith">
            <h3>EMAIL*</h3>
            <input type="email" placeholder="e.g. name@home.com">
            <h3>COMPANY</h3>
            <input type="text" placeholder="e.g. your company (optional)">
            <h3>SUBJECT</h3>
            <input type="text" placeholder="e.g. info">
            <h3>MESSAGE</h3>
            <textarea name="" id="" cols="40" rows="10"></textarea>
        </form>
        <div class="address">
            <h3>Address</h3>
            <div class="pict_p">
                <img src="{% static 'img/contact/map_icon.png' %}" alt="">
                <p> Ut interdum tristique est com modo pharetra.</p>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque aperiam voluptates mollitia
                aliquam perferendis quasi illum, dolorem velit repudiandae quam.</p>
            <div class="pict_p">
                <img src="{% static 'img/contact/phone_icon.png' %}" alt="">
                <p>1-900-324-9876</p>
            </div>
            <div class="pict_p">
                <img src="{% static 'img/contact/mail_icon.png' %}" alt="">
                <p>info@surfhouse.com</p>
            </div>
            <p>If you have questions about your order or need any general information our customer service team
                will be happy to assist you.</p>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block welcome--index %}
<div class="welcome_index">
    <div class="greet">
        <h3>WELCOME TO QUADROFLY</h3>
        <p>The only online store you will ever need for all your quadrocopter's needs</p>
    </div>
    <div class="tender">
        <h3>Quadcopter Workshop</h3>
        <p>Workshop Schedule:-Sunday, 30th April’17
        </p>
        <p>Workshop Timing:- Starts at 10:30 AM.</p>
        <a href="#">DETAILS</a>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="content">
    <div class="new">
        <h3>NEW PRODUCTS</h3>
        <!-- <div class="products_new"> -->
        {% for product in products %}
        <div>
            <a href="#">
                <img src="/media/{{ product.image }}" alt="">
            </a>
            <span><a href="">{{ product.name|upper }}</a></span>
            <span>{{ product.price }}</span>
            <!--<span> {{ product.category.name}}</span>-->
        </div>
        {% endfor %}
    </div>
    <div class="sale">
        <h3>TOP PRODUCTS</h3>
        {% for product in products %}
        <div>
            <a href="#">
                <img src="/media/{{ product.image }}" alt="">
            </a>
            <span><a href="">{{ product.name|upper }}</a></span>
            <span>{{ product.price }}</span>
            <!--<span> {{ product.category.name}}</span>-->
        </div>
        {% endfor %}
    </div>
    <div class="sale">
        <h3>SALE PRODUCTS</h3>
        {% for product in products %}
        <div>
            <a href="#">
                <img src="/media/{{ product.image }}" alt="">
            </a>
            <span><a href="">{{ product.name|upper }}</a></span>
            <span>$.{{ product.price }}</span>
            <!--<span> {{ product.category.name}}</span>-->
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}


<div class="content">
    <h4>Home >> Catalog >><span>DJI Mavic Pro</span></h4>
    <div class="product">
        <div class="product_head">
            <div class="product_image">
                <img src="/media/{{ product.image }}" alt="">
                <img src="" alt="">
                <img src="" alt="">
                <img src="" alt="">
            </div>
            <div class="product_descr">
                <h3>{{ product.name }}</h3>
                <h3>${{ product.price }}</h3>
                <hr>
                <h4>Краткое описание товара</h4>
                <p> DJI Mavic Pro является небольшим, но мощным беспилотником, который превращает небо в свой творческий
                    холст легко и непринужденно, помогая вам сделать каждый момент прекрасным. Его компактный размер
                    скрывает высокую степень сложности механизмов, что делает его одним из самых продуманных летающих
                    камер DJI, когда-либо: 24 высокопроизводительных вычислительных ядер, лучшие системы передачи
                    сигнала с 7 км диапазоном, 5 датчиков позиционирования и камера 4K, стабилизированная 3-х осевым
                    механическим стабилизатором, с помощью всего лишь одного нажатия пальца.</p>
                <hr>
                <a href="{% url 'basket:add' product.pk %}">ORDER</a>
            </div>
        </div>
        <div class="description">
            {{ product.description }}
        </div>
    </div>
</div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="content">
    <h4>Home >> Catalog >> Category >> <span> {{ category.name|title }} </span></h4>
    <div class="offer">
        {% for product in products %}
        <div>
            <a href="{% url 'products:product' product.pk %}">
                <img src="/media/{{ product.image }}" alt="">
            </a>
            <span><a href="">{{ product.name|upper }}</a></span>
            <span>$.{{ product.price }}</span>
            <a href="{% url 'basket:add' product.pk %}" class="button-order">Order</a>

        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}